### ISSUE TITLE
npm package has incorrect 'typings' field

### ISSUE THREAD

**Issue by anstarovoyt** [ngrx/db#3]
Hi. The npm package 'ngrx/db' has incorrect 'typings' field in package.json. The package doesn't have the directory 'dist' at all. See screenshot:

<img width="641" alt="screen shot 2016-06-01 at 12 35 35" src="https://cloud.githubusercontent.com/assets/1753282/15706004/3800ba26-27fa-11e6-9145-a32ad0292347.png">

**Comment by robwormald** [comment]
fixed in https://github.com/ngrx/db/commit/3577ef713d7af1bdf31fff176430f48c51679389, thanks!
