### ISSUE TITLE
Question: allow easy integration with something like localForage?

### ISSUE THREAD

**Issue by NathanWalker** [ngrx/db#5]
Just a question here. Would it be possible to architect this in such a way to make it easy to integrate with something like localForage since it also allows integration with IndexedDB as well as other nice fallbacks.

By default, use setup that's here now, but could optionally provide `localForage` if desired?

Just curious your thoughts. @MikeRyan52 @robwormald

**Comment by robwormald** [comment]
mmmm not exactly, as localForage is really just a key/value store, last I checked.... DB is designed to be much more of a proper collection focused API than localForage is, unless i'm missing your point?

**Comment by NathanWalker** [comment]
Ah ok gotcha @robwormald thanks for answer. Seems like there are some parallels but maybe not entirely... I guess the more adequate question would be are there any plans for fallbacks in using `ngrx/db` in cases where a browser didn't support `IndexedDB`?
