### ISSUE TITLE
database.js:230 Uncaught TypeError: core_1.provide is not a function

### ISSUE THREAD

**Issue by qdouble** [ngrx/db#7]
I'm not really using this, but it was in my project vendor imports. I suppose it's still using provide, which has been removed from angular master.

**Comment by metanav** [comment]
I can confirm. It is not working with Angular rc.6.

**Comment by GvRillaer** [comment]
Any idea if this will be fixed/developed further or is there an alternative?

**Comment by danielsun174** [comment]
Same problem, it seems that provide() is no longer an exported member of @angular/core

**Comment by metanav** [comment]
Yeah, need to change to {provider : 'Database',  useFactory: ...}.
I think @MikeRyan52 is doing something on the rc5 branch of example-app to circumvent this issue. Let's see when it is merge to master.

**Comment by MikeRyan52** [comment]
Should be fixed in #8

**Comment by MikeRyan52** [comment]
Resolved in v2.0.0
